/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type GlobalRanking struct {
	Country string `json:"country,omitempty"`
	FaceitElo int64 `json:"faceit_elo,omitempty"`
	GameSkillLevel int64 `json:"game_skill_level,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	PlayerId string `json:"player_id,omitempty"`
	Position int64 `json:"position,omitempty"`
}
