/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// Port An open port on a container
type Port struct {
	// Host IP address that the container's port is mapped to
	IP string `json:"IP,omitempty"`
	// Port on the container
	PrivatePort int32 `json:"PrivatePort"`
	// Port exposed on the host
	PublicPort int32 `json:"PublicPort,omitempty"`
	// type
	Type_ string `json:"Type"`
}
