/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type Role struct {
	Color string `json:"color,omitempty"`
	Name string `json:"name,omitempty"`
	Ranking int64 `json:"ranking,omitempty"`
	RoleId string `json:"role_id,omitempty"`
	VisibleOnChat bool `json:"visible_on_chat,omitempty"`
}
