/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// PluginConfigLinux plugin config linux
type PluginConfigLinux struct {
	// allow all devices
	AllowAllDevices bool `json:"AllowAllDevices"`
	// capabilities
	Capabilities []string `json:"Capabilities"`
	// devices
	Devices []PluginDevice `json:"Devices"`
}
