/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type AccessMode struct {
	BlockVolume *TypeBlock `json:"BlockVolume,omitempty"`
	MountVolume *TypeMount `json:"MountVolume,omitempty"`
	Scope *Scope `json:"Scope,omitempty"`
	Sharing *SharingMode `json:"Sharing,omitempty"`
}
