/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

import (
	"time"
)

type QueueBan struct {
	BanEnd time.Time `json:"banEnd,omitempty"`
	BanId string `json:"banId,omitempty"`
	BanStart time.Time `json:"banStart,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
	EntityId string `json:"entityId,omitempty"`
	EntityType string `json:"entityType,omitempty"`
	Expired bool `json:"expired,omitempty"`
	LastModified time.Time `json:"lastModified,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	OrganizerId string `json:"organizerId,omitempty"`
	QueueId string `json:"queueId,omitempty"`
	Reason string `json:"reason,omitempty"`
	Type_ string `json:"type,omitempty"`
	UserId string `json:"userId,omitempty"`
	Version int64 `json:"version,omitempty"`
}
