/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type OrganizerSearch struct {
	Active bool `json:"active,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	Countries []string `json:"countries,omitempty"`
	Games []string `json:"games,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizerId string `json:"organizer_id,omitempty"`
	Partner bool `json:"partner,omitempty"`
	Regions []string `json:"regions,omitempty"`
}
