/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type GameAssets struct {
	Cover string `json:"cover,omitempty"`
	FeaturedImgL string `json:"featured_img_l,omitempty"`
	FeaturedImgM string `json:"featured_img_m,omitempty"`
	FeaturedImgS string `json:"featured_img_s,omitempty"`
	FlagImgIcon string `json:"flag_img_icon,omitempty"`
	FlagImgL string `json:"flag_img_l,omitempty"`
	FlagImgM string `json:"flag_img_m,omitempty"`
	FlagImgS string `json:"flag_img_s,omitempty"`
	LandingPage string `json:"landing_page,omitempty"`
}
