/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Roster struct {
	AnticheatRequired bool `json:"anticheat_required,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	GamePlayerId string `json:"game_player_id,omitempty"`
	GamePlayerName string `json:"game_player_name,omitempty"`
	GameSkillLevel int64 `json:"game_skill_level,omitempty"`
	Membership string `json:"membership,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	PlayerId string `json:"player_id,omitempty"`
}
