/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type FilesystemChange struct {
	Kind int32 `json:"Kind"`
	// Path to file or directory that has changed.
	Path string `json:"Path"`
}
