/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type GeoLabel struct {
	En string `json:"en,omitempty"`
	Fr string `json:"fr,omitempty"`
}
