/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type TournamentTeams struct {
	CheckedIn []TournamentTeam `json:"checked_in,omitempty"`
	Finished []TournamentTeam `json:"finished,omitempty"`
	Joined []TournamentTeam `json:"joined,omitempty"`
	Started []TournamentTeam `json:"started,omitempty"`
}
