/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type ClusterVolumeSpec struct {
	AccessMode *AccessMode `json:"AccessMode,omitempty"`
	AccessibilityRequirements *TopologyRequirement `json:"AccessibilityRequirements,omitempty"`
	Availability string `json:"Availability,omitempty"`
	CapacityRange *CapacityRange `json:"CapacityRange,omitempty"`
	// Group defines the volume group of this volume. Volumes belonging to the same group can be referred to by group name when creating Services. Referring to a volume by group instructs swarm to treat volumes in that group interchangeably for the purpose of scheduling. Volumes with an empty string for a group technically all belong to the same, emptystring group.
	Group string `json:"Group,omitempty"`
	// Secrets defines Swarm Secrets that are passed to the CSI storage plugin when operating on this volume.
	Secrets []Secret `json:"Secrets,omitempty"`
}
