/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// PluginConfigRootfs plugin config rootfs
type PluginConfigRootfs struct {
	// diff ids
	DiffIds []string `json:"diff_ids,omitempty"`
	// type
	Type_ string `json:"type,omitempty"`
}
