/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// UsageData Usage details about the volume. This information is used by the `GET /system/df` endpoint, and omitted in other endpoints.
type UsageData struct {
	// The number of containers referencing this volume. This field is set to `-1` if the reference-count is not available.
	RefCount int64 `json:"RefCount"`
	// Amount of disk space used by the volume (in bytes). This information is only available for volumes created with the `\"local\"` volume driver. For volumes created with other volume drivers, this field is set to `-1` (\"not available\")
	Size int64 `json:"Size"`
}
