/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type BracketsFaction struct {
	Avatar string `json:"avatar,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	TeamId string `json:"team_id,omitempty"`
}
