/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type TournamentTeam struct {
	Nickname string `json:"nickname,omitempty"`
	SkillLevel int64 `json:"skill_level,omitempty"`
	SubsDone int64 `json:"subs_done,omitempty"`
	TeamId string `json:"team_id,omitempty"`
	TeamLeader string `json:"team_leader,omitempty"`
	TeamType string `json:"team_type,omitempty"`
}
