/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// ServiceCreateResponse contains the information returned to a client on the creation of a new service.
type ServiceCreateResponse struct {
	// The ID of the created service.
	ID string `json:"ID,omitempty"`
	// Optional warning message.  FIXME(thaJeztah): this should have \"omitempty\" in the generated type.
	Warnings []string `json:"Warnings,omitempty"`
}
