/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// DeleteResponse delete response
type DeleteResponse struct {
	// The image ID of an image that was deleted
	Deleted string `json:"Deleted,omitempty"`
	// The image ID of an image that was untagged
	Untagged string `json:"Untagged,omitempty"`
}
