/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type Faction struct {
	Avatar string `json:"avatar,omitempty"`
	FactionId string `json:"faction_id,omitempty"`
	Leader string `json:"leader,omitempty"`
	Name string `json:"name,omitempty"`
	Roster []Roster `json:"roster,omitempty"`
	RosterV1 interface{} `json:"roster_v1,omitempty"`
	Stats *Stats `json:"stats,omitempty"`
	Substituted bool `json:"substituted,omitempty"`
	Type_ string `json:"type,omitempty"`
}
