/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// OK response to ContainerCreate operation
type CreateResponse struct {
	// The ID of the created container
	Id string `json:"Id"`
	// Warnings encountered when creating the container
	Warnings []string `json:"Warnings"`
}
