/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

import (
	"time"
)

type Queue struct {
	AdminTool bool `json:"adminTool,omitempty"`
	AnticheatRequired bool `json:"anticheatRequired,omitempty"`
	CalculateElo bool `json:"calculateElo,omitempty"`
	CaptainSelection string `json:"captainSelection,omitempty"`
	CheckIn *CheckIn `json:"checkIn,omitempty"`
	EntityId string `json:"entityId,omitempty"`
	EntityType string `json:"entityType,omitempty"`
	FbiManagement bool `json:"fbiManagement,omitempty"`
	Game string `json:"game,omitempty"`
	GroupSimilar bool `json:"groupSimilar,omitempty"`
	Id string `json:"id,omitempty"`
	JoinType *JoinType `json:"joinType,omitempty"`
	LastModified time.Time `json:"lastModified,omitempty"`
	MaxSkill int64 `json:"maxSkill,omitempty"`
	MinSkill int64 `json:"minSkill,omitempty"`
	NoOfPlayers int64 `json:"noOfPlayers,omitempty"`
	Open bool `json:"open,omitempty"`
	OrganizerId string `json:"organizerId,omitempty"`
	Paused bool `json:"paused,omitempty"`
	QueueAlgorithm *QueueAlgorithm `json:"queueAlgorithm,omitempty"`
	QueueName string `json:"queueName,omitempty"`
	Region string `json:"region,omitempty"`
	State string `json:"state,omitempty"`
	VerifiedMatching bool `json:"verifiedMatching,omitempty"`
}
