/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type TeamStatsSimple struct {
	Players []PlayerStatsSimple `json:"players,omitempty"`
	Premade *interface{} `json:"premade,omitempty"`
	TeamId *interface{} `json:"team_id,omitempty"`
	TeamStats map[string]interface{} `json:"team_stats,omitempty"`
}
