/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// Info contains information about the Volume as a whole as provided by the CSI storage plugin.
type Info struct {
	// AccessibleTopolgoy is the topology this volume is actually accessible from.
	AccessibleTopology []Topology `json:"AccessibleTopology,omitempty"`
	// CapacityBytes is the capacity of the volume in bytes. A value of 0 indicates that the capacity is unknown.
	CapacityBytes int64 `json:"CapacityBytes,omitempty"`
	// VolumeContext is the context originating from the CSI storage plugin when the Volume is created.
	VolumeContext map[string]string `json:"VolumeContext,omitempty"`
	// VolumeID is the ID of the Volume as seen by the CSI storage plugin. This is distinct from the Volume's Swarm ID, which is the ID used by all of the Docker Engine to refer to the Volume. If this field is blank, then the Volume has not been successfully created yet.
	VolumeID string `json:"VolumeID,omitempty"`
}
