/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type ChampionshipStream struct {
	Active bool `json:"active,omitempty"`
	Platform string `json:"platform,omitempty"`
	Source string `json:"source,omitempty"`
	Title string `json:"title,omitempty"`
}
