/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Assets struct {
	Color string `json:"color,omitempty"`
	Icon string `json:"icon,omitempty"`
	Image string `json:"image,omitempty"`
}
