/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type SeasonDetailed struct {
	// The divisions of the given season.
	Divisions []Division `json:"divisions,omitempty"`
	Season *Season `json:"season,omitempty"`
}
