/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// CapacityRange describes the minimum and maximum capacity a volume should be created with
type CapacityRange struct {
	// LimitBytes specifies that a volume must not be bigger than this. The value of 0 indicates an unspecified maximum
	LimitBytes int64 `json:"LimitBytes,omitempty"`
	// RequiredBytes specifies that a volume must be at least this big. The value of 0 indicates an unspecified minimum.
	RequiredBytes int64 `json:"RequiredBytes,omitempty"`
}
