/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type HubStats struct {
	GameId string `json:"game_id,omitempty"`
	Players []StatsCompetitionPlayer `json:"players,omitempty"`
}
