/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type SubstitutionConfiguration struct {
	MaxSubstitutes int64 `json:"max_substitutes,omitempty"`
	MaxSubstitutions int64 `json:"max_substitutions,omitempty"`
}
