/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type RoundStats struct {
	BestOf *interface{} `json:"best_of,omitempty"`
	CompetitionId *interface{} `json:"competition_id,omitempty"`
	GameId *interface{} `json:"game_id,omitempty"`
	GameMode *interface{} `json:"game_mode,omitempty"`
	MatchId *interface{} `json:"match_id,omitempty"`
	MatchRound *interface{} `json:"match_round,omitempty"`
	Played *interface{} `json:"played,omitempty"`
	RoundStats map[string]interface{} `json:"round_stats,omitempty"`
	Teams []TeamStatsSimple `json:"teams,omitempty"`
}
