/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// ServiceUpdateResponse service update response
type ServiceUpdateResponse struct {
	// Optional warning messages
	Warnings []string `json:"Warnings,omitempty"`
}
