/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type PluginSettings struct {
	// args
	Args []string `json:"Args"`
	// devices
	Devices []PluginDevice `json:"Devices"`
	// env
	Env []string `json:"Env"`
	// mounts
	Mounts []PluginMount `json:"Mounts"`
}
