/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Rules struct {
	Body string `json:"body,omitempty"`
	Game string `json:"game,omitempty"`
	Name string `json:"name,omitempty"`
	Organizer string `json:"organizer,omitempty"`
	RuleId string `json:"rule_id,omitempty"`
}
