/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// Scope defines the Scope of a Cluster Volume. This is how many nodes a Volume can be accessed simultaneously on.
type Scope struct {
}
