/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// PluginConfigUser plugin config user
type PluginConfigUser struct {
	// g ID
	GID int32 `json:"GID,omitempty"`
	// UID
	UID int32 `json:"UID,omitempty"`
}
