/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type QueueAlgorithm struct {
	AlgorithmId string `json:"algorithmId,omitempty"`
	AlgorithmInput []string `json:"algorithmInput,omitempty"`
	AlgorithmParameters *AlgorithmParameters `json:"algorithmParameters,omitempty"`
	GeoDescription *GeoDescription `json:"geoDescription,omitempty"`
	GeoLabel *GeoLabel `json:"geoLabel,omitempty"`
	Id string `json:"id,omitempty"`
	RoleBasedCaptainPick bool `json:"roleBasedCaptainPick,omitempty"`
}
