/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// AuthenticateOKBody authenticate o k body
type AuthenticateOkBody struct {
	// An opaque token used to authenticate a user after a successful login
	IdentityToken string `json:"IdentityToken"`
	// The status of the authentication
	Status string `json:"Status"`
}
