/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Prize struct {
	FaceitPoints int64 `json:"faceit_points,omitempty"`
	Rank int64 `json:"rank,omitempty"`
}
