/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Leaderboard struct {
	CompetitionId string `json:"competition_id,omitempty"`
	CompetitionType string `json:"competition_type,omitempty"`
	EndDate int64 `json:"end_date,omitempty"`
	GameId string `json:"game_id,omitempty"`
	Group int64 `json:"group,omitempty"`
	LeaderboardId string `json:"leaderboard_id,omitempty"`
	LeaderboardMode string `json:"leaderboard_mode,omitempty"`
	LeaderboardName string `json:"leaderboard_name,omitempty"`
	LeaderboardType string `json:"leaderboard_type,omitempty"`
	MinMatches int64 `json:"min_matches,omitempty"`
	PointsPerDraw int64 `json:"points_per_draw,omitempty"`
	PointsPerLoss int64 `json:"points_per_loss,omitempty"`
	PointsPerWin int64 `json:"points_per_win,omitempty"`
	PointsType string `json:"points_type,omitempty"`
	RankingBoost int64 `json:"ranking_boost,omitempty"`
	RankingType string `json:"ranking_type,omitempty"`
	Region string `json:"region,omitempty"`
	Round int64 `json:"round,omitempty"`
	Season int64 `json:"season,omitempty"`
	StartDate int64 `json:"start_date,omitempty"`
	StartingPoints int64 `json:"starting_points,omitempty"`
	Status string `json:"status,omitempty"`
}
