/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// ContainerUpdateOKBody OK response to ContainerUpdate operation
type ContainerUpdateOkBody struct {
	// warnings
	Warnings []string `json:"Warnings"`
}
