/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit
import (
	"time"
)

type Player struct {
	ActivatedAt time.Time `json:"activated_at,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	Country string `json:"country,omitempty"`
	// Deprecated: no more in use
	CoverFeaturedImage string `json:"cover_featured_image,omitempty"`
	CoverImage string `json:"cover_image,omitempty"`
	FaceitUrl string `json:"faceit_url,omitempty"`
	FriendsIds []string `json:"friends_ids,omitempty"`
	Games map[string]GameDetail `json:"games,omitempty"`
	// Deprecated: no more in use
	Infractions *interface{} `json:"infractions,omitempty"`
	// Deprecated: use memberships instead
	MembershipType string `json:"membership_type,omitempty"`
	Memberships []string `json:"memberships,omitempty"`
	NewSteamId string `json:"new_steam_id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Platforms map[string]string `json:"platforms,omitempty"`
	PlayerId string `json:"player_id,omitempty"`
	Settings *UserSettings `json:"settings,omitempty"`
	SteamId64 string `json:"steam_id_64,omitempty"`
	SteamNickname string `json:"steam_nickname,omitempty"`
	Verified bool `json:"verified,omitempty"`
}
