/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// The Team holds information about a team.
type Team struct {
	// The Avatar of a team
	Avatar string `json:"avatar,omitempty"`
	// The ChatID of a team
	ChatRoomId string `json:"chat_room_id,omitempty"`
	// The CoverImage of a team
	CoverImage string `json:"cover_image,omitempty"`
	// The Description of a team
	Description string `json:"description,omitempty"`
	// The Facebook of a team
	Facebook string `json:"facebook,omitempty"`
	// The FaceitUrl of a team
	FaceitUrl string `json:"faceit_url,omitempty"`
	// The Game of a team
	Game string `json:"game,omitempty"`
	// The Leader of a team
	Leader string `json:"leader,omitempty"`
	// The Members of a team  Can be empty if not supported
	Members []UserSimple `json:"members,omitempty"`
	// The Name of a team
	Name string `json:"name,omitempty"`
	// The Nickname of a team
	Nickname string `json:"nickname,omitempty"`
	// The ID of a team
	TeamId string `json:"team_id,omitempty"`
	// The TeamType of a team
	TeamType string `json:"team_type,omitempty"`
	// The Twitter of a team
	Twitter string `json:"twitter,omitempty"`
	// The Website of a team
	Website string `json:"website,omitempty"`
	// The Youtube of a team
	Youtube string `json:"youtube,omitempty"`
}
