/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type Ranking struct {
	CurrentStreak int64 `json:"current_streak,omitempty"`
	Draw int64 `json:"draw,omitempty"`
	Lost int64 `json:"lost,omitempty"`
	Played int64 `json:"played,omitempty"`
	Player *UserSimple `json:"player,omitempty"`
	Points int64 `json:"points,omitempty"`
	Position int64 `json:"position,omitempty"`
	WinRate float64 `json:"win_rate,omitempty"`
	Won int64 `json:"won,omitempty"`
}
