/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type HubSmall struct {
	Avatar string `json:"avatar,omitempty"`
	FaceitUrl string `json:"faceit_url,omitempty"`
	GameId string `json:"game_id,omitempty"`
	HubId string `json:"hub_id,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizerId string `json:"organizer_id,omitempty"`
}
