/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type BirthDate struct {
	Date int64 `json:"date,omitempty"`
	Month int64 `json:"month,omitempty"`
	Year int64 `json:"year,omitempty"`
}
