/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// Plugin A plugin for the Engine API
type Plugin struct {
	Config *PluginConfig `json:"Config"`
	// True if the plugin is running. False if the plugin is not running, only installed.
	Enabled bool `json:"Enabled"`
	// Id
	Id string `json:"Id,omitempty"`
	// name
	Name string `json:"Name"`
	// plugin remote reference used to push/pull the plugin
	PluginReference string `json:"PluginReference,omitempty"`
	Settings *PluginSettings `json:"Settings"`
}
