/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type MatchHistoryPlayer struct {
	Avatar string `json:"avatar,omitempty"`
	FaceitUrl string `json:"faceit_url,omitempty"`
	GamePlayerId string `json:"game_player_id,omitempty"`
	GamePlayerName string `json:"game_player_name,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	PlayerId string `json:"player_id,omitempty"`
	SkillLevel int64 `json:"skill_level,omitempty"`
}
