/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type BracketsRound struct {
	BestOf int64 `json:"best_of,omitempty"`
	Label string `json:"label,omitempty"`
	Matches int64 `json:"matches,omitempty"`
	Round int64 `json:"round,omitempty"`
	StartTime int64 `json:"start_time,omitempty"`
	StartsAsap bool `json:"starts_asap,omitempty"`
	SubstitutionTime int64 `json:"substitution_time,omitempty"`
	SubstitutionsAllowed bool `json:"substitutions_allowed,omitempty"`
}
