/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// PublishStatus represents the status of the volume as published to an individual node
type PublishStatus struct {
	// NodeID is the ID of the swarm node this Volume is published to.
	NodeID string `json:"NodeID,omitempty"`
	// PublishContext is the PublishContext returned by the CSI plugin when a volume is published.
	PublishContext map[string]string `json:"PublishContext,omitempty"`
	State *PublishState `json:"State,omitempty"`
}
