/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type TeamStats struct {
	GameId string `json:"game_id,omitempty"`
	Lifetime map[string]interface{} `json:"lifetime,omitempty"`
	Segments []map[string]interface{} `json:"segments,omitempty"`
	TeamId string `json:"team_id,omitempty"`
}
