/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// PublishState represents the state of a Volume as it pertains to its use on a particular Node.
type PublishState struct {
}
