/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

import (
	"time"
)

type Item struct {
	Category string `json:"category,omitempty"`
	CountryBlacklist []string `json:"country_blacklist,omitempty"`
	CountryWhitelist []string `json:"country_whitelist,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	CreatedBy string `json:"created_by,omitempty"`
	// ExternalId refers to the ID of the item in a third-party shop
	ExternalId string `json:"external_id,omitempty"`
	Games []string `json:"games,omitempty"`
	Id string `json:"id,omitempty"`
	Media *ItemMedia `json:"media,omitempty"`
	Name string `json:"name,omitempty"`
	New bool `json:"new,omitempty"`
	OrderType string `json:"order_type,omitempty"`
	Platforms []string `json:"platforms,omitempty"`
	Price float32 `json:"price,omitempty"`
	Published bool `json:"published,omitempty"`
	Quantity int64 `json:"quantity,omitempty"`
	Sizes []string `json:"sizes,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Unlimited bool `json:"unlimited,omitempty"`
	Url string `json:"url,omitempty"`
}
