/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type Game struct {
	Assets *GameAssets `json:"assets,omitempty"`
	GameId string `json:"game_id,omitempty"`
	LongLabel string `json:"long_label,omitempty"`
	Order int64 `json:"order,omitempty"`
	ParentGameId string `json:"parent_game_id,omitempty"`
	Platforms []string `json:"platforms,omitempty"`
	Regions []string `json:"regions,omitempty"`
	ShortLabel string `json:"short_label,omitempty"`
}
