/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type HubUser struct {
	Avatar string `json:"avatar,omitempty"`
	FaceitUrl string `json:"faceit_url,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Roles []string `json:"roles,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
