/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// MatchmakingSlim A slim representation of a matchmaking
type MatchmakingSlim struct {
	Game string `json:"game,omitempty"`
	HasLeague bool `json:"has_league,omitempty"`
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Region string `json:"region,omitempty"`
}
