/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type Placement struct {
	DivisionName string `json:"division_name,omitempty"`
	DivisionType string `json:"division_type,omitempty"`
	Ladder string `json:"ladder,omitempty"`
	MatchmakingId string `json:"matchmaking_id,omitempty"`
	SeasonNumber int64 `json:"season_number,omitempty"`
	TierName string `json:"tier_name,omitempty"`
	TierRank int64 `json:"tier_rank,omitempty"`
}
