/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Championship struct {
	AnticheatRequired bool `json:"anticheat_required,omitempty"`
	Avatar string `json:"avatar,omitempty"`
	BackgroundImage string `json:"background_image,omitempty"`
	ChampionshipId string `json:"championship_id,omitempty"`
	ChampionshipStart int64 `json:"championship_start,omitempty"`
	CheckinClear int64 `json:"checkin_clear,omitempty"`
	CheckinEnabled bool `json:"checkin_enabled,omitempty"`
	CheckinStart int64 `json:"checkin_start,omitempty"`
	CoverImage string `json:"cover_image,omitempty"`
	CurrentSubscriptions int64 `json:"current_subscriptions,omitempty"`
	Description string `json:"description,omitempty"`
	FaceitUrl string `json:"faceit_url,omitempty"`
	Featured bool `json:"featured,omitempty"`
	Full bool `json:"full,omitempty"`
	GameData *Game `json:"game_data,omitempty"`
	GameId string `json:"game_id,omitempty"`
	// Deprecated: use championship_id instead
	Id string `json:"id,omitempty"`
	JoinChecks *JoinCheck `json:"join_checks,omitempty"`
	Name string `json:"name,omitempty"`
	OrganizerData *Organizer `json:"organizer_data,omitempty"`
	OrganizerId string `json:"organizer_id,omitempty"`
	Prizes []Prize `json:"prizes,omitempty"`
	Region string `json:"region,omitempty"`
	RulesId string `json:"rules_id,omitempty"`
	Schedule map[string]ChampionshipSchedule `json:"schedule,omitempty"`
	Screening *ChampionshipScreening `json:"screening,omitempty"`
	SeedingStrategy string `json:"seeding_strategy,omitempty"`
	Slots int64 `json:"slots,omitempty"`
	Status string `json:"status,omitempty"`
	Stream *ChampionshipStream `json:"stream,omitempty"`
	SubscriptionEnd int64 `json:"subscription_end,omitempty"`
	SubscriptionStart int64 `json:"subscription_start,omitempty"`
	SubscriptionsLocked bool `json:"subscriptions_locked,omitempty"`
	SubstitutionConfiguration *SubstitutionConfiguration `json:"substitution_configuration,omitempty"`
	TotalGroups int64 `json:"total_groups,omitempty"`
	TotalPrizes int64 `json:"total_prizes,omitempty"`
	TotalRounds int64 `json:"total_rounds,omitempty"`
	Type_ string `json:"type,omitempty"`
}
