/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type PlayerStatsSimple struct {
	Nickname interface{} `json:"nickname,omitempty"`
	PlayerId interface{} `json:"player_id,omitempty"`
	PlayerStats map[string]interface{} `json:"player_stats,omitempty"`
}
