/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// Relegation holds information about what is required in order for a player to be relegated to the previous tier.
type Relegation struct {
	// Consecutive losses needed for a player to get relegated to the previous tier.
	ConsecutiveLosses int64 `json:"consecutive_losses,omitempty"`
}
