/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type Stats struct {
	Rating int64 `json:"rating,omitempty"`
	SkillLevel *StatsSkillLevel `json:"skillLevel,omitempty"`
	WinProbability float64 `json:"winProbability,omitempty"`
}
