/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// GraphDriverData Information about the storage driver used to store the container's and image's filesystem.
type GraphDriverData struct {
	// Low-level storage metadata, provided as key/value pairs.  This information is driver-specific, and depends on the storage-driver in use, and should be used for informational purposes only.
	Data map[string]string `json:"Data"`
	// Name of the storage driver.
	Name string `json:"Name"`
}
