/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// PluginInterfaceType plugin interface type
type PluginInterfaceType struct {
	// capability
	Capability string `json:"Capability"`
	// prefix
	Prefix string `json:"Prefix"`
	// version
	Version string `json:"Version"`
}
