/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type CompetitionSearch struct {
	CompetitionId string `json:"competition_id,omitempty"`
	CompetitionType string `json:"competition_type,omitempty"`
	Game string `json:"game,omitempty"`
	Name string `json:"name,omitempty"`
	NumberOfMembers int64 `json:"number_of_members,omitempty"`
	OrganizerId string `json:"organizer_id,omitempty"`
	OrganizerName string `json:"organizer_name,omitempty"`
	OrganizerType string `json:"organizer_type,omitempty"`
	PlayersCheckedin int64 `json:"players_checkedin,omitempty"`
	PlayersJoined int64 `json:"players_joined,omitempty"`
	// Tournaments
	PrizeType string `json:"prize_type,omitempty"`
	Region string `json:"region,omitempty"`
	// Hubs
	Slots int64 `json:"slots,omitempty"`
	StartedAt int64 `json:"started_at,omitempty"`
	Status string `json:"status,omitempty"`
	TotalPrize string `json:"total_prize,omitempty"`
}
