/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type JoinType struct {
	MaxParty int64 `json:"maxParty,omitempty"`
	Party bool `json:"party,omitempty"`
	Premade bool `json:"premade,omitempty"`
	Solo bool `json:"solo,omitempty"`
}
