/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type ItemMedia struct {
	AvatarFull string `json:"avatar_full,omitempty"`
	AvatarMedium string `json:"avatar_medium,omitempty"`
	AvatarSmall string `json:"avatar_small,omitempty"`
}
