/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

import (
	"time"
)

type Order struct {
	CreatedAt time.Time `json:"created_at,omitempty"`
	Game string `json:"game,omitempty"`
	Id string `json:"id,omitempty"`
	Item *OrderItem `json:"item,omitempty"`
	Status string `json:"status,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	User *OrderUser `json:"user,omitempty"`
}
