/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

type JoinCheck struct {
	AllowedTeamTypes []string `json:"allowed_team_types,omitempty"`
	BlacklistGeoCountries []string `json:"blacklist_geo_countries,omitempty"`
	JoinPolicy string `json:"join_policy,omitempty"`
	MaxSkillLevel int64 `json:"max_skill_level,omitempty"`
	MembershipType string `json:"membership_type,omitempty"`
	MinSkillLevel int64 `json:"min_skill_level,omitempty"`
	WhitelistGeoCountries []string `json:"whitelist_geo_countries,omitempty"`
	WhitelistGeoCountriesMinPlayers int64 `json:"whitelist_geo_countries_min_players,omitempty"`
}
