/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// HistoryResponseItem individual image layer information in response to ImageHistory operation
type HistoryResponseItem struct {
	// comment
	Comment string `json:"Comment"`
	// created
	Created int64 `json:"Created"`
	// created by
	CreatedBy string `json:"CreatedBy"`
	// Id
	Id string `json:"Id"`
	// size
	Size int64 `json:"Size"`
	// tags
	Tags []string `json:"Tags"`
}
