/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// TypeMount contains options for using a volume as a Mount-type volume.
type TypeMount struct {
	// FsType specifies the filesystem type for the mount volume. Optional.
	FsType string `json:"FsType,omitempty"`
	// MountFlags defines flags to pass when mounting the volume. Optional.
	MountFlags []string `json:"MountFlags,omitempty"`
}
