/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// Volume volume
type Volume struct {
	ClusterVolume *ClusterVolume `json:"ClusterVolume,omitempty"`
	// Date/Time the volume was created.
	CreatedAt string `json:"CreatedAt,omitempty"`
	// Name of the volume driver used by the volume.
	Driver string `json:"Driver"`
	// User-defined key/value metadata.
	Labels map[string]string `json:"Labels"`
	// Mount path of the volume on the host.
	Mountpoint string `json:"Mountpoint"`
	// Name of the volume.
	Name string `json:"Name"`
	// The driver specific options used when creating the volume.
	Options map[string]string `json:"Options"`
	// The level at which the volume exists. Either `global` for cluster-wide, or `local` for machine level.
	Scope string `json:"Scope"`
	// Low-level details about the volume, provided by the volume driver. Details are returned as a map with key/value pairs: `{\"key\":\"value\",\"key2\":\"value2\"}`.  The `Status` field is optional, and is omitted if the volume driver does not support this feature.
	Status map[string]interface{} `json:"Status,omitempty"`
	UsageData *UsageData `json:"UsageData,omitempty"`
}
