/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// Can be one of:  `0`: Modified (\"C\") `1`: Added (\"A\") `2`: Deleted (\"D\")
type ChangeType struct {
}
