/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

// SharingMode defines the Sharing of a Cluster Volume. This is how Tasks using a Volume at the same time can use it.
type SharingMode struct {
}
