/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

type UserSearch struct {
	Avatar string `json:"avatar,omitempty"`
	Country string `json:"country,omitempty"`
	Games []GameUserSearch `json:"games,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	PlayerId string `json:"player_id,omitempty"`
	Status string `json:"status,omitempty"`
	Verified bool `json:"verified,omitempty"`
}
