/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package go-faceit

// Volume list response
type ListResponse struct {
	// List of volumes
	Volumes []Volume `json:"Volumes,omitempty"`
	// Warnings that occurred when fetching the list of volumes.
	Warnings []string `json:"Warnings,omitempty"`
}
