/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

type OrderUser struct {
	ExternalId string `json:"external_id,omitempty"`
	Id string `json:"id,omitempty"`
}
