/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package faceit

// PluginConfigNetwork plugin config network
type PluginConfigNetwork struct {
	// type
	Type_ string `json:"Type"`
}
