/*
 * Data API
 *
 * # This API provide access to FACEIT's data
 *
 * API version: 4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package go-faceit

import (
	"time"
)

// Season holds information about a league season. When no older season is requested, this field holds information about the season of the league.
type Season struct {
	// The end date of the season.
	EndDate time.Time `json:"end_date,omitempty"`
	// The season number.
	Number int64 `json:"number,omitempty"`
	// The placement match mount.
	PlacementMatchCount int64 `json:"placement_match_count,omitempty"`
	// The start date of the season.
	StartDate time.Time `json:"start_date,omitempty"`
}
